# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-04 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0002_auto_20190804_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontasks',
            name='finishdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persontasks',
            name='startdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persontasks',
            name='status',
            field=models.BigIntegerField(choices=[(0, 'closed'), (1, 'open')], default=1),
        ),
    ]
