# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-07-26 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0002_auto_20190726_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='userroles',
            options={'verbose_name_plural': 'UserRoles'},
        ),
    ]
