# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-07-26 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0004_auto_20190726_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermodel.UserRoles'),
        ),
    ]
