# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-04 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0005_auto_20190804_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontasks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='usermodel.Persons'),
        ),
    ]
