# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-07-29 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0006_auto_20190726_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(blank=True, max_length=50, null=True)),
                ('headquarters', models.CharField(max_length=100)),
                ('coustomer_no', models.BigIntegerField()),
            ],
            options={
                'db_table': 'CarBrand',
                'verbose_name_plural': "Car's Brand",
            },
        ),
    ]
