# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-07-30 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0007_carbrands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('contact', models.BigIntegerField()),
                ('salary', models.BigIntegerField()),
            ],
            options={
                'db_table': 'employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDesignations',
            fields=[
                ('designation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usermodel.Employees')),
                ('designation_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employeedesignation',
                'verbose_name_plural': 'EmployeeDesinations',
            },
        ),
    ]
