# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-07-30 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0009_auto_20190730_0650'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carbrands',
            table='carbrand',
        ),
    ]
