# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-07-30 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0010_auto_20190730_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrands',
            name='brandname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
