# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-07-30 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0011_auto_20190730_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Sports',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=50)),
                ('sport', models.ManyToManyField(to='usermodel.Sports')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
    ]
